// ./src/actions/actionTypes.js
const GET_ALLOCATION_DATA_SUCCESS = 'GET_ALLOCATION_DATA_SUCCESS';
const GET_ASSET_DATA_SUCCESS = 'GET_ASSET_DATA_SUCCESS';
const UPDATE_ALLOCATION_DATA = 'UPDATE_ALLOCATION_DATA';
const UPDATE_ADJUST_CASH_DATA_SUCCESS = 'UPDATE_ADJUST_CASH_DATA_SUCCESS';
const SHOW_ADJUST_CASH_MODAL = 'SHOW_ADJUST_CASH_MODAL';
const HIDE_ADJUST_CASH_MODAL = 'HIDE_ADJUST_CASH_MODAL';

export default {
  GET_ALLOCATION_DATA_SUCCESS,
  GET_ASSET_DATA_SUCCESS,
  UPDATE_ALLOCATION_DATA,
  UPDATE_ADJUST_CASH_DATA_SUCCESS,
  SHOW_ADJUST_CASH_MODAL,
  HIDE_ADJUST_CASH_MODAL
};
