// ./src/actions/actionTypes.js
const GET_ASSET_DATA_SUCCESS = 'GET_ASSET_DATA_SUCCESS';
const GET_ALLOCATION_DATA_SUCCESS = 'GET_ALLOCATION_DATA_SUCCESS';
const CLEAR_ADJUST_CASH_DATA = 'CLEAR_ADJUST_CASH_DATA';
const SHOW_ADJUST_CASH_MODAL = 'SHOW_ADJUST_CASH_MODAL';
const HIDE_ADJUST_CASH_MODAL = 'HIDE_ADJUST_CASH_MODAL';

export default {
  GET_ASSET_DATA_SUCCESS,
  GET_ALLOCATION_DATA_SUCCESS,
  CLEAR_ADJUST_CASH_DATA,
  SHOW_ADJUST_CASH_MODAL,
  HIDE_ADJUST_CASH_MODAL
};
